export type Lesson = {
  index: string;
  title: string;
  track: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  minutes: number;
  source: string;
  premise: string;
  objectives: string[];
  explanation: string;
  exercise: string;
  takeaway: string;
};

export const lessons: Lesson[] = [
  { index: "01", title: "What quantitative finance is", track: "Foundations", level: "Beginner", minutes: 12, source: "original synthesis", premise: "Quantitative finance turns assumptions about markets into models that can be measured, challenged, and improved.", objectives: ["Separate forecasting, pricing, and risk problems", "Recognize where data ends and assumptions begin", "Define an honest research question"], explanation: "A quant workflow is a chain: question, data, representation, model, decision rule, costs, and risk. A result is only as strong as its weakest link. The job is not to make equations look sophisticated; it is to make every assumption visible enough to test.", exercise: "Take one market claim you believe. Rewrite it as a measurable hypothesis with an observation window, decision time, and failure condition.", takeaway: "The model is not the market. It is a deliberately incomplete instrument for asking a precise question." },
  { index: "02", title: "Returns and compounding", track: "Foundations", level: "Beginner", minutes: 18, source: "computational-finance-course", premise: "Small choices in return definitions change aggregation, interpretation, and portfolio math.", objectives: ["Compute simple and log returns", "Compound across time correctly", "Translate between annualized and periodic quantities"], explanation: "Simple returns describe the percentage change in wealth over one interval. Log returns add across time, which makes them convenient for modeling, but portfolio aggregation happens naturally with simple returns. Annualization is a scaling convention, not a guarantee about future behavior.", exercise: "Convert a sequence of five daily prices into simple and log returns. Reconstruct the terminal price from both representations.", takeaway: "Use the return definition that matches the operation: simple across assets, logarithmic across time." },
  { index: "03", title: "Probability distributions", track: "Probability", level: "Beginner", minutes: 24, source: "computational-finance-course", premise: "A distribution is a complete statement about uncertainty, not just a mean and volatility.", objectives: ["Interpret density, CDF, and quantiles", "Compare Gaussian and heavy-tailed behavior", "Connect moments to financial risk"], explanation: "Financial outcomes are asymmetric, dependent, and often heavy-tailed. Mean and variance summarize only part of that structure. Quantiles answer threshold questions; tail expectations describe the severity beyond a threshold. Modeling begins by choosing which features of uncertainty matter for the decision.", exercise: "Compare the 1% loss quantile of a Gaussian sample with a Student-t sample calibrated to the same variance.", takeaway: "Two distributions with identical volatility can imply radically different capital requirements." },
  { index: "04", title: "Brownian motion", track: "Stochastic", level: "Intermediate", minutes: 26, source: "computational-finance-course", premise: "Brownian motion is the continuous-time noise source beneath many classical pricing models.", objectives: ["State the increment properties", "Simulate a discretized path", "Explain quadratic variation"], explanation: "Brownian increments are independent, normally distributed, and scale with the square root of elapsed time. A path is continuous but nowhere classically differentiable. This unusual roughness is exactly why ordinary calculus is replaced by stochastic calculus in continuous-time finance.", exercise: "Open the Brownian lab, change the seed, then double the time resolution. Compare path roughness and terminal dispersion.", takeaway: "Randomness accumulates with √t, not t—a scaling rule that echoes throughout risk modeling." },
  { index: "05", title: "Geometric Brownian motion", track: "Stochastic", level: "Intermediate", minutes: 28, source: "computational-finance-course", premise: "GBM converts additive Brownian shocks into positive, multiplicative price paths.", objectives: ["Derive the log-price process", "Distinguish drift from median growth", "Identify the model’s structural limits"], explanation: "Geometric Brownian motion assumes constant drift and volatility while keeping prices positive. Log prices are Gaussian, so prices are lognormal. It is mathematically convenient and central to Black–Scholes, but it cannot produce volatility clustering, jumps, or a changing return distribution.", exercise: "Simulate paths at 10%, 30%, and 70% volatility. Observe the gap between the average terminal price and the typical path.", takeaway: "A convenient state process can be useful for pricing while remaining a poor literal description of markets." },
  { index: "06", title: "Options basics", track: "Derivatives", level: "Beginner", minutes: 22, source: "computational-finance-course", premise: "An option is a nonlinear payoff with value determined by more than the probability of exercise.", objectives: ["Draw call and put payoffs", "Separate payoff from profit", "Understand moneyness and time value"], explanation: "Calls provide upside participation above a strike; puts provide downside participation below it. The premium is paid before the payoff is known, so payoff and profit are different objects. Before expiry, uncertainty and remaining time create value even when immediate exercise would produce nothing.", exercise: "Sketch payoff and profit diagrams for a long call, long put, and covered call using the same strike.", takeaway: "Option value comes from the distribution of future states, not merely today’s intrinsic value." },
  { index: "07", title: "Black–Scholes intuition", track: "Derivatives", level: "Intermediate", minutes: 20, source: "computational-finance-course", premise: "Dynamic replication, not a directional forecast, is the engine of Black–Scholes pricing.", objectives: ["Explain delta hedging", "Describe risk-neutral valuation", "Name the critical assumptions"], explanation: "If an option can be continuously replicated with the underlying and cash, its price must match the replicating portfolio or an arbitrage exists. The hedge removes instantaneous market direction from the pricing equation. Risk-neutral probabilities are therefore a valuation device, not beliefs about real-world outcomes.", exercise: "Use the Black–Scholes lab to raise volatility while holding spot and strike fixed. Explain why both call and put values increase.", takeaway: "The formula is the final line; replication is the argument that gives it meaning." },
  { index: "08", title: "The Black–Scholes equation", track: "Derivatives", level: "Advanced", minutes: 35, source: "computational-finance-course", premise: "Itô’s lemma and a self-financing hedge turn a stochastic price process into a deterministic PDE.", objectives: ["Trace the PDE derivation", "Interpret every term", "Connect boundary conditions to payoff"], explanation: "Apply Itô’s lemma to the option value, hold delta units of the underlying, and choose delta to cancel the Brownian shock. A locally riskless portfolio must earn the risk-free rate. The resulting PDE, solved with the terminal payoff as a boundary condition, yields the closed-form European option formula.", exercise: "Write the PDE and label the time decay, convexity, financing, and carry terms. Check which term dominates near expiry at-the-money.", takeaway: "The PDE is a balance sheet for local option risk." },
  { index: "09", title: "Greeks as local sensitivities", track: "Derivatives", level: "Intermediate", minutes: 30, source: "computational-finance-course", premise: "Greeks are local derivatives of a model price, not permanent facts about an instrument.", objectives: ["Interpret delta, gamma, vega, theta, and rho", "Relate gamma to hedging instability", "Understand local approximation error"], explanation: "Delta estimates price change for a small move in spot; gamma measures how quickly delta changes. Vega measures sensitivity to implied volatility, while theta captures model time decay. These quantities move with market state and depend on the chosen pricing model.", exercise: "Calculate a first-order delta estimate for a $1 spot move, then compare it with the repriced option. Attribute the gap to convexity.", takeaway: "A hedge built from stale Greeks is a new position, not the old hedge." },
  { index: "10", title: "Implied volatility", track: "Derivatives", level: "Intermediate", minutes: 27, source: "computational-finance-course", premise: "Implied volatility is the volatility input that makes a model agree with a market price.", objectives: ["Invert an option pricing model", "Read smiles and surfaces", "Avoid treating implied volatility as a direct forecast"], explanation: "There is no closed-form inverse for Black–Scholes volatility, so numerical root finding is used. Across strikes and maturities, market prices imply a surface rather than one constant number. Its shape encodes supply, demand, tail risk, and model misspecification.", exercise: "Use the implied-vol lab to recover volatility from price. Then perturb the market price and observe where inversion becomes most sensitive.", takeaway: "Implied volatility is a price coordinate—a compact language for option markets." },
  { index: "11", title: "Monte Carlo pricing", track: "Numerical", level: "Intermediate", minutes: 32, source: "financial-models-numerical-methods", premise: "Monte Carlo converts an expectation into a controlled numerical experiment.", objectives: ["Price from discounted simulated payoffs", "Measure standard error", "Use reproducible random seeds"], explanation: "Simulate terminal states under the pricing measure, evaluate the payoff in each state, average, and discount. Accuracy improves at roughly 1/√N, which is slow but broadly applicable. A point estimate without a standard error hides the numerical uncertainty that remains.", exercise: "Compare estimates at 1,000, 10,000, and 100,000 paths. Check whether the Black–Scholes value falls inside each confidence interval.", takeaway: "A simulation result is incomplete until it reports its sampling error." },
  { index: "12", title: "Heston intuition", track: "Model Zoo", level: "Advanced", minutes: 31, source: "financial-models-numerical-methods", premise: "Heston makes variance a stochastic, mean-reverting state variable correlated with price shocks.", objectives: ["Interpret κ, θ, ξ, ρ, and v₀", "Connect correlation to skew", "Recognize calibration instability"], explanation: "The variance process is pulled toward a long-run level while remaining state dependent. Correlation between spot and variance shocks allows the model to express leverage effects and implied-volatility skew. More realism adds parameters, calibration choices, and failure modes.", exercise: "Open the Heston lab. Compare paths with low and high volatility-of-volatility, then explain why price risk becomes clustered.", takeaway: "A richer model can fit more market structure, but it also creates more ways to fit noise." },
  { index: "13", title: "Mean reversion", track: "Stochastic", level: "Intermediate", minutes: 21, source: "financial-models-numerical-methods", premise: "Mean reversion is a conditional tendency toward an equilibrium—not a promise that every deviation closes.", objectives: ["Define a restoring force", "Estimate half-life", "Separate economic equilibrium from statistical average"], explanation: "A mean-reverting process has expected changes that oppose its distance from a long-run level. The speed parameter determines how quickly shocks decay in expectation. Structural breaks, drifting equilibria, and transaction costs can turn an apparent spread into a trap.", exercise: "Estimate an AR(1) coefficient for a spread and convert it to a half-life. Repeat across rolling windows.", takeaway: "Before trading reversion, test whether the equilibrium itself is stable." },
  { index: "14", title: "Ornstein–Uhlenbeck", track: "Model Zoo", level: "Advanced", minutes: 29, source: "financial-models-numerical-methods", premise: "The OU process is a continuous-time Gaussian model for noisy movement around a long-run level.", objectives: ["Solve the conditional mean", "Relate κ to half-life", "Identify where Gaussian support is unrealistic"], explanation: "The process combines deterministic pull toward θ with Brownian noise. Its conditional distribution is Gaussian and its variance approaches a stationary limit. That makes estimation tractable, but it can produce negative values and assumes a fixed equilibrium and noise scale.", exercise: "Use the OU lab to change the starting value and volatility. Observe how the expected pull differs from path-by-path behavior.", takeaway: "Mean reversion describes a distribution of future states, not a deterministic return path." },
  { index: "15", title: "Feature leakage", track: "Research", level: "Intermediate", minutes: 19, source: "machine-learning-for-trading", premise: "A model leaks when training inputs contain information that would not exist at the prediction timestamp.", objectives: ["Detect target and preprocessing leakage", "Build time-aware transformations", "Audit feature availability"], explanation: "Leakage can enter through labels, global normalization, revised fundamentals, or cross-validation that ignores time. It often creates impressive validation scores precisely because the model is solving an easier, impossible problem. Every feature needs an as-of timestamp.", exercise: "For five candidate features, write the earliest timestamp at which each value becomes knowable. Quarantine any feature that cannot answer clearly.", takeaway: "If the feature matrix knows the future, the backtest is a data-quality bug report." },
  { index: "16", title: "Look-ahead bias", track: "Backtesting", level: "Beginner", minutes: 16, source: "machine-learning-for-trading", premise: "Look-ahead bias lets a historical decision use data published or finalized later.", objectives: ["Distinguish event time from availability time", "Spot close-to-close timing errors", "Design a point-in-time test"], explanation: "Daily bars, index constituents, and financial statements all have release conventions. Joining by calendar date can quietly place future information into a past decision. A valid backtest models when data was observable and when an order could realistically execute.", exercise: "Draw a timestamp timeline for signal calculation, data availability, order submission, and fill. Look for impossible ordering.", takeaway: "Correct values at the wrong time are still wrong data." },
  { index: "17", title: "Survivorship bias", track: "Backtesting", level: "Beginner", minutes: 18, source: "machine-learning-for-trading", premise: "Testing only today’s survivors removes many historical failures from the opportunity set.", objectives: ["Construct a point-in-time universe", "Recognize delisting bias", "Measure the effect on results"], explanation: "Current constituents and active securities are selected by what survived. Historical tests using them inherit knowledge of the future and usually overstate quality. Delisted names, corporate actions, and membership dates are part of the dataset—not edge cases.", exercise: "Compare a strategy on current index members with a point-in-time constituent history. Report the performance and turnover gaps.", takeaway: "A universe is a time series, not a static list." },
  { index: "18", title: "Transaction costs", track: "Backtesting", level: "Intermediate", minutes: 23, source: "machine-learning-for-trading", premise: "A gross signal becomes a strategy only after spread, impact, borrow, fees, and delay.", objectives: ["Model turnover-linked costs", "Distinguish spread from market impact", "Stress capacity assumptions"], explanation: "Costs depend on what, when, and how much you trade. Crossing the spread is only the beginning; larger orders move the market, hard-to-borrow positions charge rent, and delayed fills change exposure. Cost sensitivity should be visible before a result is promoted.", exercise: "Recompute a backtest at 0, 5, 15, and 40 basis points per turn. Find the break-even cost and its implied capacity.", takeaway: "If a strategy dies under a small realistic cost, it never existed net of implementation." },
  { index: "19", title: "Backtest validation", track: "Research", level: "Advanced", minutes: 34, source: "machine-learning-for-trading", premise: "Validation measures how a research process generalizes—not how well one chosen curve explains the past.", objectives: ["Use walk-forward evaluation", "Separate selection from final testing", "Account for repeated experiments"], explanation: "Time-aware splits preserve causal order. Hyperparameter selection belongs inside training folds, and the final holdout should remain untouched until the process is frozen. When many ideas are tried, the best observed result is partly a selection statistic.", exercise: "Design an expanding-window validation scheme with training, tuning, embargo, and final test periods. State what may change at each stage.", takeaway: "The unit being validated is the full decision process, including selection." },
  { index: "20", title: "Portfolio optimization basics", track: "Portfolio", level: "Intermediate", minutes: 30, source: "financial-models-numerical-methods", premise: "Portfolio construction converts uncertain forecasts into constrained exposures.", objectives: ["Read expected return and covariance inputs", "Interpret the efficient frontier", "Understand estimation error"], explanation: "Mean–variance optimization trades expected return against variance. The mathematics is clean; the inputs are not. Small errors in expected returns can create extreme weights, so constraints, shrinkage, and robust alternatives are often more important than a more precise solver.", exercise: "Perturb one asset’s expected return by 1%. Measure the change in optimal weights with and without position limits.", takeaway: "Optimization amplifies input confidence—deserved or not." },
];

export type ModelRecord = {
  name: string;
  family: string;
  status: string;
  accent: "lime" | "amber" | "blue";
  note: string;
  equation: string;
  intuition: string;
  assumptions: string[];
  failure: string;
};

export const models: ModelRecord[] = [
  { name: "Black–Scholes–Merton", family: "Diffusion", status: "LAB LIVE", accent: "lime", note: "Closed-form European option pricing under lognormal diffusion.", equation: "dSₜ = μSₜdt + σSₜdWₜ", intuition: "A continuously rebalanced stock-and-cash portfolio replicates the option’s local risk.", assumptions: ["Continuous trading", "Constant volatility and rate", "No jumps or transaction costs", "European exercise"], failure: "Volatility smiles, jumps, discrete hedging, dividends, and liquidity make the hedge imperfect." },
  { name: "Geometric Brownian Motion", family: "Stochastic process", status: "LAB LIVE", accent: "lime", note: "Positive price paths with constant drift and volatility.", equation: "Sₜ = S₀ exp[(μ − σ²/2)t + σWₜ]", intuition: "Proportional random shocks accumulate in log price while spot stays positive.", assumptions: ["Independent increments", "Constant drift", "Constant volatility", "Lognormal prices"], failure: "Real returns cluster, jump, skew, and change regime." },
  { name: "Heston", family: "Stochastic volatility", status: "LAB LIVE", accent: "amber", note: "Mean-reverting variance with leverage-sensitive dynamics.", equation: "dvₜ = κ(θ − vₜ)dt + ξ√vₜdWᵛₜ", intuition: "Variance is its own random state and can rise when spot falls through negative correlation.", assumptions: ["Continuous paths", "Square-root variance", "Stable long-run variance", "Constant parameters"], failure: "Calibration can be unstable and short-dated jumps remain poorly represented." },
  { name: "Merton Jump Diffusion", family: "Lévy / jumps", status: "LAB LIVE", accent: "amber", note: "Lognormal diffusion plus discontinuous compound-Poisson jumps.", equation: "dS/S = (μ − λk)dt + σdW + (J − 1)dN", intuition: "Most moves are continuous, but occasional events arrive with random size.", assumptions: ["Poisson jump arrivals", "Independent jump sizes", "Constant intensity", "Lognormal diffusion between jumps"], failure: "Jump intensity and size distribution can change exactly when markets become stressed." },
  { name: "Ornstein–Uhlenbeck", family: "Mean reversion", status: "LAB LIVE", accent: "amber", note: "Gaussian process pulled toward a long-run level.", equation: "dXₜ = κ(θ − Xₜ)dt + σdWₜ", intuition: "The farther state moves from equilibrium, the stronger its expected pull back.", assumptions: ["Fixed equilibrium", "Constant reversion speed", "Gaussian shocks", "Stationary parameters"], failure: "Structural breaks and drifting equilibria make historical reversion misleading." },
  { name: "Kalman Filter", family: "State space", status: "LAB LIVE", accent: "blue", note: "Recursive latent-state estimation under linear Gaussian noise.", equation: "x̂ₜ|ₜ = x̂ₜ|ₜ₋₁ + Kₜ(yₜ − Hx̂ₜ|ₜ₋₁)", intuition: "Blend a model forecast with a noisy observation according to their relative uncertainty.", assumptions: ["Linear transition", "Gaussian noise", "Known covariance structure", "Correct state specification"], failure: "Nonlinearity, outliers, and covariance misspecification create overconfident estimates." },
  { name: "Mean–Variance", family: "Portfolio", status: "LAB LIVE", accent: "blue", note: "Expected-return and covariance trade-offs under constraints.", equation: "max wᵀμ − (λ/2)wᵀΣw", intuition: "Choose weights that pay enough expected return for their modeled contribution to portfolio variance.", assumptions: ["Single-period decision", "Stable mean and covariance", "Variance represents risk", "Frictionless rebalancing"], failure: "Noisy forecasts can produce concentrated and unstable weights." },
];

export const pipeline = [
  { index: "01", name: "DATA", copy: "Build a point-in-time, bias-aware research universe.", checklist: ["Record observation and availability timestamps", "Preserve delisted securities", "Version every raw input"], failure: "Using a cleaned current universe to explain the past." },
  { index: "02", name: "FEATURES", copy: "Transform observations without leaking the future.", checklist: ["Fit transforms inside each training fold", "Lag data to its true availability", "Document missing-value rules"], failure: "Global normalization learns from the holdout period." },
  { index: "03", name: "MODELS", copy: "Fit the simplest model that can test the hypothesis.", checklist: ["Define a naive baseline", "Bound model complexity", "Track every experiment"], failure: "Complexity substitutes for a clear hypothesis." },
  { index: "04", name: "VALIDATION", copy: "Use time-aware splits and honest model selection.", checklist: ["Preserve causal order", "Nest hyperparameter selection", "Keep one final untouched test"], failure: "The test set becomes another training set through repeated inspection." },
  { index: "05", name: "BACKTEST", copy: "Translate predictions into explicit trading rules.", checklist: ["State signal time and order time", "Model feasible fills", "Reconcile positions and cash"], failure: "Predictions are evaluated without a realizable portfolio rule." },
  { index: "06", name: "COSTS", copy: "Model turnover, spreads, impact, borrow, and delay.", checklist: ["Stress multiple cost levels", "Model liquidity by instrument", "Report capacity assumptions"], failure: "Every order fills instantly at the midpoint." },
  { index: "07", name: "PORTFOLIO", copy: "Turn signals into constrained exposures and weights.", checklist: ["Cap concentration", "Neutralize unintended factors", "Model rebalance policy"], failure: "A small forecast difference creates an extreme allocation." },
  { index: "08", name: "RISK", copy: "Stress assumptions, tails, concentration, and failure modes.", checklist: ["Run historical and hypothetical shocks", "Expose factor and liquidity concentration", "Write kill conditions"], failure: "Risk is reduced to one backward-looking volatility number." },
] as const;

export const tools = [
  { name: "QuantLib", workflow: "Pricing", language: "C++ / Python", access: "Open source", url: "https://github.com/lballabio/QuantLib" },
  { name: "PyPortfolioOpt", workflow: "Portfolio", language: "Python", access: "Open source", url: "https://github.com/robertmartin8/PyPortfolioOpt" },
  { name: "vectorbt", workflow: "Backtesting", language: "Python", access: "Open source", url: "https://github.com/polakowo/vectorbt" },
  { name: "statsmodels", workflow: "Time series", language: "Python", access: "Open source", url: "https://github.com/statsmodels/statsmodels" },
  { name: "Riskfolio-Lib", workflow: "Risk", language: "Python", access: "Open source", url: "https://github.com/dcajasn/Riskfolio-Lib" },
  { name: "TA-Lib", workflow: "Indicators", language: "C / Python", access: "Open source", url: "https://github.com/TA-Lib/ta-lib" },
  { name: "Zipline", workflow: "Backtesting", language: "Python", access: "Open source", url: "https://github.com/quantopian/zipline" },
  { name: "mlfinlab", workflow: "ML workflow", language: "Python", access: "Commercial", url: "https://github.com/hudson-and-thames/mlfinlab" },
  { name: "FinQuant", workflow: "Portfolio", language: "Python", access: "Open source", url: "https://github.com/fmilthaler/FinQuant" },
  { name: "QuantConnect LEAN", workflow: "Research engine", language: "C# / Python", access: "Open source", url: "https://github.com/QuantConnect/Lean" },
] as const;

export const graves = [
  { name: "THE SHARPE MIRAGE", cause: "Overfit parameters", note: "A beautiful in-sample ratio produced by repeated selection.", symptom: "Performance collapses when parameters move slightly or the sample advances.", diagnosis: "The search process selected noise and the reported Sharpe ignored the number of trials.", repair: "Freeze a selection protocol, use nested walk-forward validation, and report parameter sensitivity.", test: "Does a broad neighborhood of settings survive a genuinely untouched period?" },
  { name: "THE TIME TRAVELER", cause: "Look-ahead bias", note: "Tomorrow’s close quietly entered today’s feature set.", symptom: "Fills look uncannily precise and results change when signals are delayed one bar.", diagnosis: "The backtest aligned data by date instead of the moment each value became observable.", repair: "Track availability timestamps and enforce signal, order, and fill sequencing.", test: "Can every feature value be reconstructed using only information available at decision time?" },
  { name: "THE IMMORTAL INDEX", cause: "Survivorship bias", note: "Dead securities vanished from the historical universe.", symptom: "The strategy favors persistent winners and rarely encounters delistings or distressed names.", diagnosis: "Today’s constituents were projected backward, importing knowledge of future survival.", repair: "Use point-in-time memberships, delisting returns, and historical security masters.", test: "At each rebalance, could the strategy have known exactly this universe?" },
  { name: "THE FREE FILL", cause: "Transaction costs", note: "Every order filled at mid with infinite liquidity.", symptom: "The edge scales without limit and turnover appears harmless.", diagnosis: "The simulator omitted spread, impact, borrow, delay, or participation constraints.", repair: "Model costs by instrument and size, then stress them well beyond the base case.", test: "What cost level erases the edge, and is that level plausible for the intended capacity?" },
  { name: "THE LEAKY LABEL", cause: "Feature leakage", note: "Preprocessing learned from observations beyond the training fold.", symptom: "Cross-validation is excellent while live or forward performance is ordinary.", diagnosis: "A transform, label, or imputation rule used data from outside its training window.", repair: "Fit the entire preprocessing pipeline independently inside each temporal fold.", test: "If the future rows are deleted, are all historical feature values unchanged?" },
  { name: "THE REGIME TOURIST", cause: "Non-stationarity", note: "One market regime was mistaken for a permanent law.", symptom: "The strategy works in one volatility, rate, or liquidity environment and fails elsewhere.", diagnosis: "The estimated relationship was conditional on a regime the model treated as universal.", repair: "Validate across regimes, add monitoring, reduce leverage, and define kill conditions.", test: "Which observable state variables explain when the edge disappears?" },
] as const;

export const sources = [
  { id: "awesome-quant", repo: "wilsonfreitas/awesome-quant", commit: "9289247", branch: "main", license: "No root license detected", surface: "Quant Stack" },
  { id: "computational-finance-course", repo: "LechGrzelak/Computational-Finance-Course", commit: "f2c192d", branch: "main", license: "BSD-3-Clause", surface: "Derivatives School" },
  { id: "machine-learning-for-trading", repo: "stefan-jansen/machine-learning-for-trading", commit: "4592d5b", branch: "main", license: "MIT", surface: "Research Pipeline" },
  { id: "financial-models-numerical-methods", repo: "cantaro86/Financial-Models-Numerical-Methods", commit: "585ed19", branch: "master", license: "AGPL-3.0 — isolated", surface: "Model Zoo" },
];

export const quests = [
  "Price a call without memorizing the formula",
  "Prove put–call parity numerically",
  "Catch the time traveler",
  "Build a point-in-time split",
  "Estimate Monte Carlo error",
  "Stress a volatility assumption",
  "Autopsy a free-fill backtest",
  "Map one model to three tools",
  "Find the hidden regime change",
  "Ship a cited research memo",
];
